apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        development
        image: sit722acr9.azurecr.io/frontend:latest   # ✅ workflow will override ta
        main
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:                                          # ✅ added env vars
        - name: PRODUCT_API_URL
          value: "http://product-service-w08e1:80"
        - name: ORDER_API_URL
          value: "http://order-service-w08e1:80"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-w08e1
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer