name: CD - Deploy Backend Services to AKS

on:
  workflow_call: # Only callable from backend-ci
    inputs:
      aks_cluster_name:
        required: true
        type: string
      aks_resource_group:
        required: true
        type: string
      aks_acr_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    environment: Production

    outputs:
      PRODUCT_API_IP: ${{ steps.get_product_ip.outputs.external_ip }}
      ORDER_API_IP: ${{ steps.get_order_ip.outputs.external_ip }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        run: |
          az aks get-credentials --resource-group ${{ inputs.aks_resource_group }} \
                                 --name ${{ inputs.aks_cluster_name }} \
                                 --overwrite-existing

      - name: Deploy Backend Infrastructure
        run: |
          kubectl apply -f k8s/configmaps.yaml
          kubectl apply -f k8s/secrets.yaml
          kubectl apply -f k8s/product-db.yaml
          kubectl apply -f k8s/order-db.yaml

      - name: Deploy Backend Microservices
        run: |
          kubectl apply -f k8s/product-service.yaml
          kubectl apply -f k8s/order-service.yaml

      - name: Update Backend Images with Correct Tag
        run: |
          kubectl set image deployment/product-service \
            product-service=${{ inputs.aks_acr_name }}.azurecr.io/product_service:${{ inputs.image_tag }} -n default
          kubectl set image deployment/order-service \
            order-service=${{ inputs.aks_acr_name }}.azurecr.io/order_service:${{ inputs.image_tag }} -n default

      - id: get_product_ip
        run: echo "external_ip=$(kubectl get service product-service-w08e1 -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT

      - id: get_order_ip
        run: echo "external_ip=$(kubectl get service order-service-w08e1 -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT